name: Build
description: Build bcftools
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: git clone --depth 1 https://github.com/samtools/bcftools

    - name: Preconfigure
      shell: bash
      working-directory: bcftools
      run: autoreconf

    - name: Configure
      shell: bash
      working-directory: bcftools
      run: CFLAGS="-s USE_ZLIB=1 -s USE_BZIP2=1" emconfigure ./configure --host none --without-curses --with-htslib=../htslib

    - name: Build
      shell: bash
      working-directory: bcftools
      run: emmake make bcftools CFLAGS="-s USE_ZLIB=1 -s USE_BZIP2=1 -O3 -DNDEBUG" LDFLAGS="-s EXIT_RUNTIME=1 -s EXPORT_ES6=1 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_RUNTIME_METHODS=[\\\"callMain\\\",\\\"FS\\\"] -s ENVIRONMENT=[\\\"web\\\"] -O3 -DNDEBUG"

    - name: Rename
      shell: bash
      working-directory: bcftools
      run: mv bcftools bcftools.js

    - name: Make dist directory
      shell: bash
      run: mkdir -p dist/wasm/bcftools

    - name: Copy artifacts to dist
      shell: bash
      run: cp bcftools/bcftools.js bcftools/bcftools.wasm -t dist/wasm/bcftools/
