name: Build
description: Build vcftools
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: git clone --depth 1 https://github.com/vcftools/vcftools

    - name: Autogen
      shell: bash
      working-directory: vcftools
      run: autoreconf -i

    - name: Configure
      shell: bash
      working-directory: vcftools
      run: emconfigure ./configure --host none CXXFLAGS="-std=c++14" ZLIB_CFLAGS="-s USE_ZLIB=1" ZLIB_LIBS="-s USE_ZLIB=1"

    - name: Build
      shell: bash
      working-directory: vcftools/src/cpp
      run: make EXEEXT=.js vcftools.js CXXFLAGS="-std=c++14 -O3 -DNDEBUG" LDFLAGS="-s EXPORT_ES6=1 -s MODULARIZE=1 -s EXPORTED_RUNTIME_METHODS=[\"callMain\",\"FS\"] -s ENVIRONMENT=[\"web\"]"

    - name: Make dist directory
      shell: bash
      run: mkdir -p dist/wasm/vcftools

    - name: Copy artifacts to dist
      shell: bash
      run: cp vcftools/src/cpp/vcftools.js vcftools/src/cpp/vcftools.wasm -t dist/wasm/vcftools/
