name: Build
description: Build ncbi-blast
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.17.0+-src.tar.gz -O - | tar xz

    - name: Patch
      shell: bash
      working-directory: ncbi-blast-2.17.0+-src/c++
      run: patch -p0 < ../../recipes/blast/blast-2.17.0.patch

    - name: Configure and build native datatools
      shell: bash
      working-directory: ncbi-blast-2.17.0+-src/c++
      run: ./configure --with-projects=scripts/projects/datatool/project.lst --with-build-root=native && make -j$(nproc) -C native/build all_p

    - name: Configure with emscripten
      shell: bash
      working-directory: ncbi-blast-2.17.0+-src/c++
      run: emconfigure ./configure --host=wasm32-unknown-none AR="emar cr" CXXFLAGS="-s USE_SQLITE3=1 -O0" --with-build-root=wasm --with-static --without-dll --without-debug --without-mt --without-openmp --without-gmp --without-ftds --without-opengl --without-z --without-bz2 --without-pcre --without-pcre2 --without-lmdb --without-boost --without-check --without-strip --with-projects=scripts/projects/blast/project.lst

    - name: Build
      shell: bash
      working-directory: ncbi-blast-2.17.0+-src/c++
      run: NCBI_DATATOOL_PATH="$(realpath native/bin)" make -j$(nproc) -C wasm/build CXXFLAGS="-fwasm-exceptions -s USE_SQLITE3=1 -O3" LDFLAGS="-fwasm-exceptions -s USE_SQLITE3=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s STACK_SIZE=1048576 -s EXIT_RUNTIME=1 -s EXPORT_ES6=1 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_RUNTIME_METHODS=[\"callMain\",\"FS\"] -s ENVIRONMENT=[\"web\"] -O3 -DNDEBUG" all_p

    - name: Make dist directory
      shell: bash
      run: mkdir -p dist/wasm/blast

    - name: Copy artifacts to dist
      shell: bash
      run: |
          for f in blast/blastn blast/blastp blast/blastx blast/deltablast blast/psiblast blast/rpsblast blast/rpstblastn blastdb/makeblastdb blastdb/makeclusterdb blastdb/makeprofiledb; do
              cp ncbi-blast-2.17.0+-src/c++/wasm/build/app/$f dist/wasm/blast/${f##*/}.js
              cp ncbi-blast-2.17.0+-src/c++/wasm/build/app/$f.wasm dist/wasm/blast/
          done
