name: Build
description: Build clustalw
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: wget ftp://ftp.ebi.ac.uk/pub/software/clustalw2/2.1/clustalw-2.1.tar.gz && tar -xvzf clustalw-2.1.tar.gz

    - name: Patch
      shell: bash
      working-directory: clustalw-2.1
      run: patch -p0 < ../recipes/clustalw/clustalw-2.1.patch

    - name: Configure
      shell: bash
      working-directory: clustalw-2.1
      run: emconfigure ./configure --host none CXXFLAGS="-std=c++98 -O0"

    - name: Build
      shell: bash
      working-directory: clustalw-2.1/src
      run: make EXEEXT=.js clustalw2.js CXXFLAGS="-std=c++98 -O3 -DNDEBUG" LDFLAGS="-s EXPORT_ES6=1 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_RUNTIME_METHODS=[\"callMain\",\"FS\"] -s ENVIRONMENT=[\"web\"]"

    - name: Make dist directory
      shell: bash
      run: mkdir -p dist/wasm/clustalw

    - name: Copy artifacts to dist
      shell: bash
      run: cp clustalw-2.1/src/clustalw2.js clustalw-2.1/src/clustalw2.wasm -t dist/wasm/clustalw/
