name: Build
description: Build sed
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: git clone --depth 1 https://github.com/mirror/sed

    - name: Clone submodules
      shell: bash
      working-directory: sed
      run: git clone --depth 1 https://github.com/mirror/gnulib

    - name: Bootstrap
      shell: bash
      working-directory: sed
      run: GNULIB_SRCDIR=gnulib ./bootstrap

    - name: Configure
      shell: bash
      working-directory: sed
      run: emconfigure ./configure --host=none CFLAGS="-O0" ac_cv_have_decl_alarm=no gl_cv_func_sleep_works=yes --disable-threads

    - name: Build
      shell: bash
      working-directory: sed
      run: make EXEEXT=.js sed/sed.js CFLAGS="-O3 -DNDEBUG" LDFLAGS="-s EXPORT_ES6=1 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_RUNTIME_METHODS=[\"callMain\",\"FS\"] -s ENVIRONMENT=[\"web\"]"

    - name: Make dist directory
      shell: bash
      run: mkdir -p dist/wasm/sed

    - name: Copy artifacts to dist
      shell: bash
      run: cp sed/sed/sed.js sed/sed/sed.wasm -t dist/wasm/sed/
