name: Build
description: Build sed
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: wget https://ftp.gnu.org/gnu/sed/sed-4.9.tar.gz && tar -xvzf sed-4.9.tar.gz

    - name: Configure
      shell: bash
      working-directory: sed-4.9
      run: emconfigure ./configure --host=none CFLAGS="-O0" ac_cv_have_decl_alarm=no gl_cv_func_sleep_works=yes --disable-threads

    - name: Build
      shell: bash
      working-directory: sed-4.9
      run: make EXEEXT=.js sed/sed.js CFLAGS="-O3 -DNDEBUG" LDFLAGS="-s EXPORT_ES6=1 -s MODULARIZE=1 -s EXPORTED_RUNTIME_METHODS=[\"callMain\",\"FS\"]"

    - name: Make dist directory
      shell: bash
      run: mkdir -p dist/wasm/sed

    - name: Copy artifacts to dist
      shell: bash
      run: cp sed-4.9/sed/sed.js sed-4.9/sed/sed.wasm -t dist/wasm/sed/
