name: Build
description: Build gawk
runs:
  using: "composite"
  steps:
    - name: Clone
      shell: bash
      run: git clone --depth 1 https://github.com/sailfishos-mirror/gawk

    - name: Configure
      shell: bash
      working-directory: gawk
      run: emconfigure ./configure --host none CFLAGS="-O0"

    - name: Build support
      shell: bash
      working-directory: gawk/support
      run: make

    - name: Build gawk
      shell: bash
      working-directory: gawk
      run: make EXEEXT=.js CFLAGS="-O3 -DNDEBUG" LDFLAGS="-s EXPORT_ES6=1 -s MODULARIZE=1 -s EXPORTED_RUNTIME_METHODS=[\"callMain\",\"FS\"] -s ENVIRONMENT=[\"web\"]" gawk.js

    - name: Make dist directory
      shell: bash
      run: mkdir -p dist/wasm/gawk

    - name: Copy artifacts to dist
      shell: bash
      run: cp gawk/gawk.js gawk/gawk.wasm -t dist/wasm/gawk/
