name: Publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-1:
    name: Build set 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create dist directory
        run: mkdir ./dist

      - name: Setup emscripten
        uses: emscripten-core/setup-emsdk@v15

      - name: Build aster
        uses: ./.github/actions/build-aster

      - name: Build bedtools
        uses: ./.github/actions/build-bedtools

      - name: Build clustalw
        uses: ./.github/actions/build-clustalw

      - name: Build fasttree
        uses: ./.github/actions/build-fasttree

      - name: Build gffread
        uses: ./.github/actions/build-gffread

      - name: Build lastz
        uses: ./.github/actions/build-lastz

      - name: Build quicktree
        uses: ./.github/actions/build-quicktree

      - name: Build raxml
        uses: ./.github/actions/build-raxml

      - name: Build seqtk
        uses: ./.github/actions/build-seqtk

      - name: Build vcftools
        uses: ./.github/actions/build-vcftools

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-set-1
          path: ./dist

  build-2:
    name: Build set 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create dist directory
        run: mkdir ./dist

      - name: Setup emscripten
        uses: emscripten-core/setup-emsdk@v15

      - name: Build htslib
        uses: ./.github/actions/build-htslib

      - name: Build samtools
        uses: ./.github/actions/build-samtools

      - name: Build bcftools
        uses: ./.github/actions/build-bcftools

      - name: Build sed
        uses: ./.github/actions/build-sed

      - name: Build gawk
        uses: ./.github/actions/build-gawk

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-set-2
          path: ./dist

  build-3:
    name: Build set 3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create dist directory
        run: mkdir ./dist

      - name: Setup emscripten
        uses: emscripten-core/setup-emsdk@v15

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Build kalign
        uses: ./.github/actions/build-kalign

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-set-3
          path: ./dist

  build-4:
    name: Build set 4
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create dist directory
        run: mkdir ./dist

      - name: Setup emscripten
        uses: emscripten-core/setup-emsdk@v15

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Build blast
        uses: ./.github/actions/build-blast

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-set-4
          path: ./dist

  publish:
    needs: [build-1, build-2, build-3, build-4]
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create dist directory
        run: mkdir ./dist

      - name: Copy static files
        run: cp -r ./package.json ./js -t ./dist/

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          path: ./dist
          pattern: build-set-*
          merge-multiple: true

      - name: Build wasm.js
        working-directory: dist/wasm
        run: ls **/*.js | sed 's/.js//' | awk "{print \"export { default as '\"\$0\"' } from '../wasm/\"\$0\".js';\" }" > ../js/wasm.js

      - name: Build manifest
        run: python ../build_manifest.py wasm > manifest.json
        working-directory: dist

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 24
          package-manager-cache: false

      - name: Publish package to npm
        working-directory: dist
        run: npm publish --provenance
